// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcFJ4LQ5ELUFsN3_m-xoS3TvS2mkxnxOI',
    appId: '1:378947858418:web:41c1cee0a58781db0d056b',
    messagingSenderId: '378947858418',
    projectId: 'shopswift-project',
    authDomain: 'shopswift-project.firebaseapp.com',
    storageBucket: 'shopswift-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkTOefNUcJSvj5USVOBzMqou5PfcW1CA4',
    appId: '1:378947858418:android:1c085abbbf793c670d056b',
    messagingSenderId: '378947858418',
    projectId: 'shopswift-project',
    storageBucket: 'shopswift-project.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcFJ4LQ5ELUFsN3_m-xoS3TvS2mkxnxOI',
    appId: '1:378947858418:web:e1f0acc5dbdbdd680d056b',
    messagingSenderId: '378947858418',
    projectId: 'shopswift-project',
    authDomain: 'shopswift-project.firebaseapp.com',
    storageBucket: 'shopswift-project.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8PNtWLWWGvM-54_Pf5F_AJTk03OPgF-w',
    appId: '1:378947858418:ios:92560013c05b7a390d056b',
    messagingSenderId: '378947858418',
    projectId: 'shopswift-project',
    storageBucket: 'shopswift-project.firebasestorage.app',
    iosBundleId: 'com.example.adminpanelapp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8PNtWLWWGvM-54_Pf5F_AJTk03OPgF-w',
    appId: '1:378947858418:ios:92560013c05b7a390d056b',
    messagingSenderId: '378947858418',
    projectId: 'shopswift-project',
    storageBucket: 'shopswift-project.firebasestorage.app',
    iosBundleId: 'com.example.adminpanelapp',
  );

}